import { AuthProvider } from '@/lib/context/AuthContext';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { Toaster } from 'react-hot-toast';
import '../styles/game-zone.css';
import '../styles/header.css';
import '../styles/loading-game.css';
import '../styles/money.css';
import '../styles/notice.css';
import '../styles/other-menu.css';
import '../styles/swiper.css';
import './globals.css';
import NextUiProvider from './NextUiProvider';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextUiProvider>
          <AuthProvider>
            {children}
            <Toaster />
          </AuthProvider>
        </NextUiProvider>
      </body>
    </html>
  );
}
